# First Playbook
- name: Upgrade K8s Controllers
  hosts: controller-0

  vars:
    gig_ssh_command:
      http_proxy: 'ssh -i /home/ubuntu/.ssh/gh_ssh_key -o IdentitiesOnly=yes -o LogLevel=quiet'

  tasks: 
  - name: Pull Latest Upgrade Script from VSC & Run
    ansible.builtin.shell: |
      cd {{ upgrade_scripts_dir }}
      git pull
      {{ upgrade_controller_command }} &> /tmp/cron/git.log
    args: 
      executable: /bin/bash
    environment: "{{ git_ssh_command }}"
    