# First Playbook
- name: Upgrade K8s Controllers
  hosts: controller-0

  tasks: 
  - name: Pull Latest Upgrade Script from VSC & Run
    ansible.builtin.shell: |
      cd {{ upgrade_scripts_dir }}
      git pull
      {{ upgrade_controller_command }} &> {{ UPGRADE_LOG }}
    args: 
      executable: /bin/bash
    environment: 
      GIT_SSH_COMMAND: "ssh -i /home/ubuntu/.ssh/gh_ssh_key -o IdentitiesOnly=yes -o LogLevel=quiet"
      UPGRADE_LOG: /tmp/controller-upgrade-error.log
    