# First Playbook
- name: Upgrade K8s Controllers
  hosts: controller-0

  tasks: 
  - name: Pull Latest
    ansible.builtin.shell: |
      cd {{ upgrade_scripts_dir }}
      git pull
    args: 
      executable: /bin/bash
    environment: 
      GIT_SSH_COMMAND: "ssh -i /home/ubuntu/.ssh/gh_ssh_key -o IdentitiesOnly=yes -o LogLevel=quiet"
  - name: Run Upgrade
    ansible.builtin.shell: |
      cd {{ upgrade_scripts_dir }}
      mkdir -p /tmp/ansible
      {{ upgrade_controller_command }} &> {{ ansible_upgrade_log }}
    args: 
      executable: /bin/bash
